stages:
  - build
  - post-build

build-image:
  stage: build
  image: docker:20.10.18-git
  services:
    - docker:20.10.18-dind
  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger"
    - if: $CI_PIPELINE_SOURCE == "web"
  variables:
    DOCKER_DRIVER: overlay2
  timeout: 120m
  script:
    - |
      export PIPELINE="$CI_COMMIT_BRANCH"
      ./build.sh && echo 'success' > .build-status || ( echo 'failed' > .build-status && exit 1 )
  artifacts:
    paths:
      - .build-status
    when: always
    expire_in: never

send-notification:
  stage: post-build
  image: alpine:3.14.8
  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger"
    - if: $CI_PIPELINE_SOURCE == "web"
  when: always
  script:
    - |
      apk add --no-cache curl
      export BUILD_STATUS=$( cat .build-status )
      export X_CI_WEBHOOK_SECRET_HEADER="x-gitlab-webhook-secret: $X_GITLAB_WEBHOOK_SECRET"
      ./notify.sh
