stages:
  - build
  - post-build

build-image:
  stage: build
  image: docker:18.09.2-git
  services:
    - docker:18.09.2-dind
  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger"
    - if: $CI_PIPELINE_SOURCE == "web"
  variables:
    DOCKER_DRIVER: overlay2
  timeout: 120m
  script:
    - |
      export PIPELINE="$CI_COMMIT_BRANCH"
      ./build.sh

send-notification:
  stage: post-build
  image: alpine:3.8
  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger"
    - if: $CI_PIPELINE_SOURCE == "web"
  when: always
  script:
    - |
      ./notify.sh
