trigger:
  - none

variables:
  BUILD_DIR: 'build/'
  UPDATE_DIR: 'update/'

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  workspace:
    clean: all
  continueOnError: false
  timeoutInMinutes: 90
  steps:
  - script: |
      whoami
      cat /etc/*release
      lscpu
      df -h
      free
      docker info
      docker version
    displayName: 'System Info'
  - script: |
      set -e
      # Process variables
      PIPELINE="${BUILD_SOURCEBRANCHNAME}"
      if [ "${APPID}" = 90 ]; then
          REPOSITORY="${REGISTRY_GOLDSOURCE}/${GAME}"
          GAME_ENGINE="hlds"
      else
          REPOSITORY="${REGISTRY_SOURCE}/${GAME}"
          GAME_ENGINE="srcds"
      fi

      echo "${REGISTRY_PASSWORD}" | docker login -u "${REGISTRY_USER}" --password-stdin

      # Set job-scoped variables
      echo "##vso[task.setvariable variable=PIPELINE]${PIPELINE}"
      echo "##vso[task.setvariable variable=REPOSITORY]${REPOSITORY}"
      echo "##vso[task.setvariable variable=GAME_ENGINE]${GAME_ENGINE}"
      echo "##vso[task.setvariable variable=GAME_BIN]${GAME_BIN}"
    env:
      REGISTRY_PASSWORD: $(REGISTRY_PASSWORD)
    displayName: 'Before Script'
  - script: |
      set -e
      date
      # Build / Update the game image
      if [ "${PIPELINE}" = 'build' ]; then
          GAME_IMAGE="${REPOSITORY}:${GAME_VERSION}"
          if [ "${CACHE}" = 'true' ]; then
              docker pull "${GAME_IMAGE}" || true
          fi
          docker build \
              --cache-from "${GAME_IMAGE}" \
              --build-arg APPID="${APPID}" \
              --build-arg MOD="${MOD}" \
              --build-arg FIX_APPMANIFEST="${FIX_APPMANIFEST}" \
              --build-arg CLIENT_APPID="${CLIENT_APPID}" \
              -t "${GAME_IMAGE}" \
              --label "appid=${APPID}" \
              --label "mod=${MOD}" \
              --label "client_appid=${CLIENT_APPID}" \
              --label "game=${GAME}" \
              --label "game_version=${GAME_VERSION}" \
              --label "game_update_count=0" \
              --label "game_engine=${GAME_ENGINE}" \
              "${BUILD_DIR}"
          if [ "${LATEST}" = 'true' ]; then
              docker tag "${GAME_IMAGE}" "${REPOSITORY}:latest"
          fi
      elif [ "${PIPELINE}" = 'update' ]; then
          GAME_IMAGE="${REPOSITORY}:latest"
          docker pull "${GAME_IMAGE}"
          docker build \
          --build-arg GAME_IMAGE="${GAME_IMAGE}" \
          -t "${GAME_IMAGE}" \
          --label "game_version=${GAME_VERSION}" \
          --label "game_update_count=${GAME_UPDATE_COUNT}" \
          "${UPDATE_DIR}"
          docker tag "${GAME_IMAGE}" "${REPOSITORY}:${GAME_VERSION}-layered"
      fi
      date
      echo; docker images
      echo; docker inspect "${GAME_IMAGE}"
      echo; docker history "${GAME_IMAGE}"

      # Set job-scoped variables
      echo "##vso[task.setvariable variable=GAME_IMAGE]${GAME_IMAGE}"
    displayName: 'Pipeline: $(Build.SourceBranchName), GAME: $(GAME), APPID: $(APPID), GAME_VERSION: $(GAME_VERSION)'
  - script: |
      set -e
      # Test the game image
      if [ ! "${NO_TEST}" = 'true' ]; then
          if [ -z "${GAME_BIN}" ]; then
              if [ "${APPID}" = 90 ]; then
                  GAME_BIN="hlds_linux"
              else
                  GAME_BIN="srcds_linux"
              fi
          fi
          if [ -z "${GAME_LAUNCH_OPTS}" ]; then
              GAME_LAUNCH_OPTS="-game ${GAME}"
          fi
          GAME_TEST_CMD="${GAME_BIN} ${GAME_LAUNCH_OPTS} +version +exit"
          echo "Game test command: ${GAME_TEST_CMD}"
          date
          docker run \
              -t \
              --rm \
              "${GAME_IMAGE}" \
              "printenv && echo && ls -al && echo && exec ${GAME_TEST_CMD}"
          echo; date
      fi
    displayName: 'Test Game Image'
  - script: |
      set -e
      # Push the image
      if [ ! "${NO_PUSH}" = 'true' ]; then
          date
          docker push "${REPOSITORY}"
          date
      fi
    displayName: 'Push Game Image'
  - script: |
      docker logout
    displayName: 'After Script'
    condition: always()