trigger: none
pr: none

jobs:
- job: Linux
  pool:
    vmImage: ubuntu-20.04
  workspace:
    clean: all
  timeoutInMinutes: 120
  steps:
  - script: |
      export PIPELINE="$BUILD_SOURCEBRANCHNAME"
      ./build.sh
    env:
      REGISTRY_PASSWORD: $(REGISTRY_PASSWORD)
      STEAM_USERNAME: $(STEAM_USERNAME)
      STEAM_PASSWORD: $(STEAM_PASSWORD)
    displayName: Build, test, push image
