name: ci-master-pr

on:
  push:
    branches:
    - master
    tags:
    - '**'
  pull_request:
    branches:
    - master

jobs:
  test-build-hlds:
    runs-on: ubuntu-20.04
    if: github.event_name != 'pull_request' || github.repository_owner != 'startersclan'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test
      run: |
        set -a
        . test/build-hlds-cstrike.env
        ./build.sh
      env:
        STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
        STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}

  test-update-hlds:
    runs-on: ubuntu-20.04
    if: github.event_name != 'pull_request' || github.repository_owner != 'startersclan'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test
      run: |
        set -a
        . test/update-hlds-cstrike.env
        ./build.sh
      env:
        STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
        STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}

  test-build-srcds:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test
      run: |
        set -a
        . test/build-srcds-hl2mp.env
        ./build.sh
      env:
        STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
        STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}

  test-update-srcds:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test
      run: |
        set -a
        . test/update-srcds-hl2mp.env
        ./build.sh
      env:
        STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
        STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
